[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#00B0F0"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[browser]
gatherUsageStats = false

[global]
disableWatchdogWarning = true
showWarningOnDirectExecution = false
